version: '3.7'

services:
  postgres:
    image: postgres:11
    container_name: golang_example_db
    volumes:
      - golang_example:/var/libs/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=developer
      - POSTGRES_DB=golang_example_db
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
    networks:
      - net

volumes:
  golang_example:

networks:
  net:
    driver: bridge
